name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Build and test with Maven
      run: mvn clean test

    - name: Test Results
      if: always()
      run: |
        if [ -f "target/surefire-reports/TEST-com.example.TransliteratorTest.xml" ]; then
          echo "✅ Тесты выполнены успешно!"
          echo "Отчеты тестов доступны в target/surefire-reports/"
        else
          echo "❌ Тесты не были выполнены или завершились с ошибкой"
          exit 1
        fi

    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-reports
        path: target/surefire-reports/
        retention-days: 7

  status:
    name: Test Status
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
    - name: Success
      if: needs.test.result == 'success'
      run: |
        echo "🎉 Все тесты прошли успешно!"
        echo "✅ Build passing"

    - name: Failure
      if: needs.test.result == 'failure'
      run: |
        echo "❌ Тесты не прошли. Пожалуйста, проверьте отчеты."
        exit 1